# Generated by Django 6.0.2 on 2026-03-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HclsWebApi', '0007_checklogin_phone_checklogin_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklogin',
            name='admin_type',
            field=models.IntegerField(choices=[(1, 'Managerial Admin'), (2, 'Operational Admin')], default=1),
        ),
    ]
