# Generated by Django 6.0.2 on 2026-03-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HclsWebApi', '0008_checklogin_admin_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklogin',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='checklogin',
            name='username',
        ),
        migrations.AlterField(
            model_name='checklogin',
            name='admin_type',
            field=models.CharField(choices=[(1, 'MAdmin'), (2, 'OpAdmin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='checklogin',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='checklogin',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
