# Generated by Django 6.0.2 on 2026-03-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HclsWebApi', '0009_remove_checklogin_phone_remove_checklogin_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklogin',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='checklogin',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
